include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    flutter_style_todos: false
    library_private_types_in_public_api: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    - 'scripts/**'
    - 'bricks/**'
    - "**/*.g.dart"
    - "**/*.config.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
